### ISSUE TITLE
Latest NMC daemon not working with p2pool.

### ISSUE THREAD

**Issue by p3yot3** [namecoin/namecoin-core#49]
The latest client seems to be broken with p2pool - I've been getting these errors repeatedly since updating:

2015-12-07 00:37:59.409856 > Error while calling merged getauxblock on http://127.0.0.1:7333/:
2015-12-07 00:37:59.409981 > Traceback (most recent call last):
2015-12-07 00:37:59.410021 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
2015-12-07 00:37:59.410057 >     current.result = callback(current.result, *args, **kw)
2015-12-07 00:37:59.410091 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1155, in gotResult
2015-12-07 00:37:59.410124 >     _inlineCallbacks(r, g, deferred)
2015-12-07 00:37:59.410157 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2015-12-07 00:37:59.410192 >     result = result.throwExceptionIntoGenerator(g)
2015-12-07 00:37:59.410226 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2015-12-07 00:37:59.410262 >     return g.throw(self.type, self.value, self.tb)
2015-12-07 00:37:59.410294 > --- <exception caught here> ---
2015-12-07 00:37:59.410326 >   File "/home/rig/p2pool/p2pool/util/deferral.py", line 41, in f
2015-12-07 00:37:59.410359 >     result = yield func(*args, **kwargs)
2015-12-07 00:37:59.410391 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2015-12-07 00:37:59.410424 >     result = result.throwExceptionIntoGenerator(g)
2015-12-07 00:37:59.410456 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2015-12-07 00:37:59.410490 >     return g.throw(self.type, self.value, self.tb)
2015-12-07 00:37:59.410523 >   File "/home/rig/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
2015-12-07 00:37:59.410558 >     raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
2015-12-07 00:37:59.410593 > p2pool.util.jsonrpc.NarrowError: -1 CreateNewBlock: TestBlockValidity failed:  (code 0)

**Comment by JeremyRand** [comment]
What was the most recent version of Namecoin Core that you know worked?  Hopefully that'll help narrow down what caused the issue.

**Comment by p3yot3** [comment]
A reboot fixed it for a day or so, but I am now seeing the error again:

2015-12-10 10:44:18.838600 > Error while calling merged getauxblock on http://127.0.0.1:7333/:
2015-12-10 10:44:18.838814 > Traceback (most recent call last):
2015-12-10 10:44:18.838921 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
2015-12-10 10:44:18.839041 >     current.result = callback(current.result, *args, **kw)
2015-12-10 10:44:18.839087 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1155, in gotResult
2015-12-10 10:44:18.839129 >     _inlineCallbacks(r, g, deferred)
2015-12-10 10:44:18.839157 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2015-12-10 10:44:18.839186 >     result = result.throwExceptionIntoGenerator(g)
2015-12-10 10:44:18.839214 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2015-12-10 10:44:18.839245 >     return g.throw(self.type, self.value, self.tb)
2015-12-10 10:44:18.839307 > --- <exception caught here> ---
2015-12-10 10:44:18.839335 >   File "/home/rig/p2pool/p2pool/util/deferral.py", line 41, in f
2015-12-10 10:44:18.839362 >     result = yield func(*args, **kwargs)
2015-12-10 10:44:18.839389 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2015-12-10 10:44:18.839418 >     result = result.throwExceptionIntoGenerator(g)
2015-12-10 10:44:18.839444 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2015-12-10 10:44:18.839473 >     return g.throw(self.type, self.value, self.tb)
2015-12-10 10:44:18.839499 >   File "/home/rig/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
2015-12-10 10:44:18.839528 >     raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
2015-12-10 10:44:18.839557 > p2pool.util.jsonrpc.NarrowError: -1 CreateNewBlock: TestBlockValidity failed:  (code 0)

This is using the latest daemon version pulled from git on Xubuntu 64bit:

  "version": 129900,
  "protocolversion": 110012,
  "walletversion": 60000,

**Comment by p3yot3** [comment]
I updated from git again but the problem is still there:

7.0.0.1:7333/:
2015-12-12 14:17:22.629642 > Traceback (most recent call last):
2015-12-12 14:17:22.629669 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
2015-12-12 14:17:22.629695 >     current.result = callback(current.result, *args, **kw)
2015-12-12 14:17:22.629719 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1155, in gotResult
2015-12-12 14:17:22.629743 >     _inlineCallbacks(r, g, deferred)
2015-12-12 14:17:22.629766 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2015-12-12 14:17:22.629790 >     result = result.throwExceptionIntoGenerator(g)
2015-12-12 14:17:22.629814 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2015-12-12 14:17:22.629839 >     return g.throw(self.type, self.value, self.tb)
2015-12-12 14:17:22.629862 > --- <exception caught here> ---
2015-12-12 14:17:22.629884 >   File "/home/rig/p2pool/p2pool/util/deferral.py", line 41, in f
2015-12-12 14:17:22.629906 >     result = yield func(*args, **kwargs)
2015-12-12 14:17:22.629929 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2015-12-12 14:17:22.629952 >     result = result.throwExceptionIntoGenerator(g)
2015-12-12 14:17:22.629975 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2015-12-12 14:17:22.629999 >     return g.throw(self.type, self.value, self.tb)
2015-12-12 14:17:22.630021 >   File "/home/rig/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
2015-12-12 14:17:22.630045 >     raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
2015-12-12 14:17:22.630070 > p2pool.util.jsonrpc.NarrowError: -1 CreateNewBlock: TestBlockValidity failed:  (code 0)

**Comment by domob1812** [comment]
My guess is that this is related to the recent upstream rewrite of `CreateNewBlock`.  This broke the regression tests for Namecoin, but I fixed them.  Maybe the fix did not go far enough, although I'm not sure what the remaining problem could be.  The regression tests indicate that basic name operations including mining and "everything" work.

**Comment by p3yot3** [comment]
Just to make sure, I'm currently doing a reindex in case my data is corrupted in some way - but I'm pretty sure it's not. I'm no coder I'm afraid, so can't offer any meaningful input, just the basics (logs etc). If I still get the errors after reindexing I'll revert back to the last working version.

**Comment by flound1129** [comment]
In the most recent code, getblocktemplate stops working after a few days with a CreateNewBlock error.  I'll get the error the next time it happens and post it here.

**Comment by p3yot3** [comment]
Just pulled the latest version - still have the same error I'm afraid.

**Comment by flound1129** [comment]
$ namecoin-cli getblocktemplate
error code: -1
error message:
CreateNewBlock: TestBlockValidity failed:  (code 0)

Getting lots of these in the debug log:
2015-12-23 06:35:18 CreateNewBlock(): total size 1246 txs: 1 fees: 500000 sigops 101
2015-12-23 06:35:18 ERROR: CheckNameTransaction: NAME_FIRSTUPDATE on an unexpired name
2015-12-23 06:35:18 ERROR: CheckInputs: tx invalid for Namecoin
2015-12-23 06:35:18 ERROR: ConnectBlock(): CheckInputs on fc56b9f2297a299cf59022317b50ba45ace9392932453eb027f3a77bf4c90bb1 failed with  (code 0)

**Comment by domob1812** [comment]
I think this is the same as https://github.com/namecoin/namecoin-core/issues/50, closing here.  A fix for the other issue is incoming - please reopen here if this persists.
